/// Flutter icons ExpenseIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExpenseIcon
///      fonts:
///       - asset: fonts/ExpenseIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExpenseIcon {
  ExpenseIcon._();

  static const _kFontFam = 'ExpenseIcon';
  static const String? _kFontPkg = null;

  static const IconData expense = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
