/// Flutter icons PieChartIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PieChartIcon
///      fonts:
///       - asset: fonts/PieChartIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PieChartIcon {
  PieChartIcon._();

  static const _kFontFam = 'PieChartIcon';
  static const String? _kFontPkg = null;

  static const IconData pie_chart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
