/// Flutter icons TransactionIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TransactionIcon
///      fonts:
///       - asset: fonts/TransactionIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TransactionIcon {
  TransactionIcon._();

  static const _kFontFam = 'TransactionIcon';
  static const String? _kFontPkg = null;

  static const IconData transaction = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
