/// Flutter icons ArrowForward
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrowForward
///      fonts:
///       - asset: fonts/ArrowForward.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArrowForward {
  ArrowForward._();

  static const _kFontFam = 'ArrowForward';
  static const String? _kFontPkg = null;

  static const IconData arrow_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
