/// Flutter icons ArrowRight
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrowRight
///      fonts:
///       - asset: fonts/ArrowRight.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArrowRight {
  ArrowRight._();

  static const _kFontFam = 'ArrowRight';
  static const String? _kFontPkg = null;

  static const IconData arrow_right = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
