/// Flutter icons NavLeft
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavLeft
///      fonts:
///       - asset: fonts/NavLeft.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavLeft {
  NavLeft._();

  static const _kFontFam = 'NavLeft';
  static const String? _kFontPkg = null;

  static const IconData arrow_left = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
