/// Flutter icons SalaryIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SalaryIcon
///      fonts:
///       - asset: fonts/SalaryIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SalaryIcon {
  SalaryIcon._();

  static const _kFontFam = 'SalaryIcon';
  static const String? _kFontPkg = null;

  static const IconData salary =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
