/// Flutter icons ShoppingIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ShoppingIcon
///      fonts:
///       - asset: fonts/ShoppingIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ShoppingIcon {
  ShoppingIcon._();

  static const _kFontFam = 'ShoppingIcon';
  static const String? _kFontPkg = null;

  static const IconData shopping_bag =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
