/// Flutter icons ArrowDown
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArrowDown
///      fonts:
///       - asset: fonts/ArrowDown.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArrowDown {
  ArrowDown._();

  static const _kFontFam = 'ArrowDown';
  static const String? _kFontPkg = null;

  static const IconData arrow_down = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
