/// Flutter icons SuccessIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuccessIcon
///      fonts:
///       - asset: fonts/SuccessIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SuccessIcon {
  SuccessIcon._();

  static const _kFontFam = 'SuccessIcon';
  static const String? _kFontPkg = null;

  static const IconData success =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
