// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbu1BZvEtO-5AHhABUot9tNkh68kk5Pm0',
    appId: '1:267281332935:web:06158fe36d21202ce31ce2',
    messagingSenderId: '267281332935',
    projectId: 'expensepro-efd45',
    authDomain: 'expensepro-efd45.firebaseapp.com',
    storageBucket: 'expensepro-efd45.appspot.com',
    measurementId: 'G-587FX3H55D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgzD4zxvv0jlpOcpC8hiMAOuVfud-pF_U',
    appId: '1:267281332935:android:c77537de0cddabd9e31ce2',
    messagingSenderId: '267281332935',
    projectId: 'expensepro-efd45',
    storageBucket: 'expensepro-efd45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQn8XwHpRUdBqr-UYNDjIfimC4Zipo4g',
    appId: '1:267281332935:ios:50f4b71878e0fc8ae31ce2',
    messagingSenderId: '267281332935',
    projectId: 'expensepro-efd45',
    storageBucket: 'expensepro-efd45.appspot.com',
    androidClientId: '267281332935-7oa5vp8ur3hesko66t37c2jj047qq6n8.apps.googleusercontent.com',
    iosClientId: '267281332935-davio3o5m799cek065urh5mdc9rl3gu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQn8XwHpRUdBqr-UYNDjIfimC4Zipo4g',
    appId: '1:267281332935:ios:50f4b71878e0fc8ae31ce2',
    messagingSenderId: '267281332935',
    projectId: 'expensepro-efd45',
    storageBucket: 'expensepro-efd45.appspot.com',
    androidClientId: '267281332935-7oa5vp8ur3hesko66t37c2jj047qq6n8.apps.googleusercontent.com',
    iosClientId: '267281332935-davio3o5m799cek065urh5mdc9rl3gu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensePro',
  );
}
